language: go

go_import_path: 4d63.com/vangen

go:
  - 1.9
  - tip

os:
  - linux
  - osx

script:
  - go test -coverprofile=coverage.txt ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
